### ISSUE TITLE
How to install percritic itself (on Linux)?

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [oschwald/SublimeLinter-perlcritic#10]
Sorry if I am being obtuse, but . .

> To install perlcritic, type `cpanm perlcritic`.

```
$ cpanm perlcritic
bash: cpanm: command not found
$ sudo apt install perlcritic
[. . .]
E: Unable to locate package perlcritic
$ sudo apt install cpanm
[. . .]
E: Unable to locate package cpanm
$ apt list perlc*
[. . .]
perlconsole/jammy,jammy 0.4-4.1 all
```

**Comment by nerdstrike** [comment]
`Provided by: [libperl-critic-perl_1.140-1_all](https://launchpad.net/ubuntu/jammy/+package/libperl-critic-perl)`
https://manpages.ubuntu.com/manpages/jammy/man1/perlcritic.1p.html

or

`cpanm Perl::Critic`

**Comment by LinuxOnTheDesktop** [comment]
Thank you (though something went wrong with your formatting).
