### ISSUE TITLE
ModernPerl not recognized with Package Control installatation of linter-contrib-perlcritic

### ISSUE THREAD

**Issue by piengeng** [oschwald/SublimeLinter-perlcritic#3]
HI, i'm not sure if this is real issue, i did a fresh install of sublime text3 and package control, the ```SublimeLinter-contrib-perlcritic``` doesn't seems to recognize ModernPerl and I have to modify the ```linter.py``` to get it working.

**Comment by oschwald** [comment]
Thanks for pointing that out. The package control version was a number of commits behind this version. It should now be up to date.
