### ISSUE TITLE
Some of links from README.md are dead

### ISSUE THREAD

**Issue by elvenfighter** [oschwald/SublimeLinter-perlcritic#4]
Links (URLs), pointing at  https://github.com/SublimeLinter/SublimeLinter.github.io/wiki/ are leading to a the 404 page.

More exactly, these two are dead:
https://github.com/SublimeLinter/SublimeLinter.github.io/wiki/Settings
https://github.com/SublimeLinter/SublimeLinter.github.io/wiki/Linter-Settings

**Comment by oschwald** [comment]
These appear to have been fixed by #5. Thanks for reporting!
